### ISSUE TITLE
Indicate when the extension is on/off

### ISSUE THREAD

**Issue by sammyshj** [privly/privly-safari#29]
Presently, we can stop the extension by clicking on `Stop Injecting`. However, to denote the running state of the extension, there is no on/off visual.
In Safari extensions, we cannot have a modal button so the best thing to do in my opinion, is to have 2 different images, one with the on and one with the off text. Once the `Stop Injecting` is pressed, the image with the off text will be shown as the image of the toolbar item. On clicking `Start Injecting`, the image of the toolbar will be change again.
@smcgregor What do you think about this approach?

**Comment by smcgregor** [comment]
Sounds good.
