### ISSUE TITLE
Package Safari Extension

### ISSUE THREAD

**Issue by smcgregor** [privly/privly-safari#42]
Let's package the extension and see if there is a way to preview it from Apple's servers before publishing to the world.

**Comment by sammyshj** [comment]
Does this mean adding the packaged Safari extension as a release in the `privly-safari` repo?

**Comment by smcgregor** [comment]
Not yet. Let's work out the build and private publishing process, then mint a new version number with a release tag in the repo.

**Comment by sammyshj** [comment]
For releasing a Safari extension on the Safari Extensions Gallery, we need to have a Apple Developer Program Membership. More about this can be read from, https://developer.apple.com/safari/extensions/
So, I think the best thing to do is to build the extension using Extension Builder and then have a new version number with a release tag in the same repo.

**Comment by smcgregor** [comment]
I signed up for this a while back. Shall I attempt to package and publish
to it? I want to treat the first version as more of a preview than a
general release.

**Comment by sammyshj** [comment]
I have packaged the extension and it can be seen at, https://github.com/sammyshj/privly-safari/blob/download/privly.safariextension/privly.safariextz?raw=true
Please let me know if you can publish the package to the Safari Extensions Gallery. Thanks!

**Comment by smcgregor** [comment]
I'll take care of this next week. I'll also push a develop branch now that we are releasing versions.

**Comment by smcgregor** [comment]
I paid the $99 Apple tax and I am awaiting account activation.

**Comment by sammyshj** [comment]
Any updates on this?

**Comment by smcgregor** [comment]
I invited you to be a "member" of my team, but it isn't clear what the implications of membership are. I think [this site](https://developer.apple.com/membercenter/index.action#home) only matters insofar as we need to sign the extension with a key known to Apple?

**Comment by sammyshj** [comment]
It looks like I can submit the Safari extension at, https://developer.apple.com/safari/extensions/submission/
Should I go ahead and do that?

**Comment by smcgregor** [comment]
The Foundation needs to have control of pushing new versions to users, so I suppose I'll build the extension and submit this form. Do you have a screen capture you want to use? I'll fill in the rest.

**Comment by sammyshj** [comment]
I did not find any option of pushing a version to only the users of an organisation. I did try uploading the extension but I did not hear back from them till now.
They have specified the dimensions of the images to be used. Attached are the images.
![rsz_logo_290](https://cloud.githubusercontent.com/assets/4390022/9742895/e31cbaaa-5680-11e5-9226-6f3cc643d01f.png)
![rsz_screen_shot_2015-09-06_at_51437_pm](https://cloud.githubusercontent.com/assets/4390022/9742896/e31e4be0-5680-11e5-8483-2d520c9478ed.png)

**Comment by smcgregor** [comment]
It would be better to have a screen capture from a normal looking website. When you submitted the extension, was it associated with the Privly Foundation's developer account?

**Comment by sammyshj** [comment]
Yes, I agree on having a screen capture from a normal looking website.
While submitting the extension, it wasn't specified as to which account was associated with the same.
I think it will be better if you can submit the extension from your side associating it to the Privly Foundation's developer account.

**Comment by sammyshj** [comment]
The updated screen capture is attached.
![rsz_screen_shot_2015-09-09_at_41638_am](https://cloud.githubusercontent.com/assets/4390022/9749383/2d1477d2-56aa-11e5-9a3e-6924ea50eca7.png)

**Comment by smcgregor** [comment]
1. I am creating a directory on https://priv.ly to host the extension.
2. The [directions](https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/DistributingYourExtension/DistributingYourExtension.html) indicate that I must "Include a link to a copy of your .safariextz folder on your website." The .safariextz folder will be a signed archived folder, correct? Will there always be a single current and distributed version of the extension with this as the file name?
3. I will need to ask our host, the Open Source Lab, to change the MIME type to "application/octet-stream", with `AddType application/octet-stream .safariextz`

@sammyshj Can you update [this page](https://priv.ly/pages/download.html) to include Safari once we have Apple distributing it?

**Comment by sammyshj** [comment]
2. The .safariextz folder is already signed with my developer ID. This lets other users install the extension. There can be multiple versions out of the same extension and all of them must be signed with the developer ID.

Yes, I will update the page to include Safari. Before that, I will update this repo, to add automatic updating of the extension once the extension is hosted on https://priv.ly/

**Comment by smcgregor** [comment]
I signed it with the key for the privly@privly.org email and [pushed it to my fork](https://github.com/smcgregor/privly.github.io/commit/86a87ec7a7e19912d2b5b8252a99315a9111f307). Does this look good to you? I'll merge and deploy.

**Comment by sammyshj** [comment]
Yes, I tested the uploaded extension with Safari and it works good. It can be merged now.
Thanks!

**Comment by smcgregor** [comment]
You can see the staging version [here](http://privly.github.io/assets/extensions/safari/privly.safariextz). I'll deploy to priv.ly if this looks good to you. We may need to change the MIME type for the file with the host for this to work.

**Comment by sammyshj** [comment]
Yes, this looks good to me. I will update this repo soon so that the extension can be uploaded on the Safari Extensions Gallery. Thanks.

**Comment by sammyshj** [comment]
@smcgregor The extension is now hosted on the Safari Extensions Gallery, so, this issue can be closed now.
