### ISSUE TITLE
Integrate Karma Test Runner

### ISSUE THREAD

**Issue by sammyshj** [privly/privly-safari#9]

**Comment by smcgregor** [comment]
I believe the steps involved in implementing this are to:

1. Add a launcher to [package list](https://github.com/privly/privly-applications/blob/master/test/package.json) that will launch the safari web browser.
2. Add Safari to [this list](https://github.com/privly/privly-applications/blob/master/test/karma.conf.js#L97). When doing this step you should also figure out a way to _not_ run the tests on Safari if Safari is not present. I don't know if trying to run safari on a platform that doesn't have it will throw an error.
3. Finally, run the tests on SauceLabs using [the other Karma configuration script.](https://github.com/privly/privly-applications/blob/master/test/karma.conf-ci.js#L57)
